### ISSUE TITLE
Avoid pzduniak/argon2, it's not up to date

### ISSUE THREAD

**Issue by pzduniak** [bbuck/dragon-mud#82]
My port of libargon2 implements an old, vulnerable version of the algorithm. Unfortunately I don't think that there is any pure Go implementation with a full featureset, but the closest you can get is go-argon2 using CGo, there's also my fork which includes the C code, so that the whole library is self-contained.

**Comment by bbuck** [comment]
First off, thank you very much for bringing that to my attention!

Is there no way to update the pure Go implementation? I, admittedly, am not as familiar with things like cryptographic programming as I'd like to be. If possible though I could pursue a PR against your library to bring it all into the Go world? 

I'm trying to avoid CGo altogether, which is why I'm using a Go implementation of Lua (even though it's about 3x slower than the C implementation).
